spring.application.name=demo
spring.data.mongodb.uri=mongodb+srv://prince21182_db_user:u1YTb1sqeBJQKSb6@cluster0.uz6uptp.mongodb.net/textile
server.error.include-stacktrace=always

# Firebase Admin SDK
firebase.service-account.path=indiantextileconnect-firebase-adminsdk-fbsvc-525030a804.json

# File Upload Settings
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB
app.upload.dir=src/main/resources/static/uploads
# Razorpay Integration
razorpay.key=rzp_test_SZCwHDTqlm3cvo
razorpay.secret=76Ju3OFCaH6Uh7eEYuZmac3H
